application: sakbot-py
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: hello.app

env_variables:
  SLACK_OUTGOING_TOKEN: __slack_outgoing_webhook_token__
  SLACK_WEBHOOK_URL: https://hooks.slack.com/services/.....
